//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApp.PrinterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrinterService.IPrinterServ")]
    public interface IPrinterServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrinterServ/Print", ReplyAction="http://tempuri.org/IPrinterServ/PrintResponse")]
        void Print(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrinterServ/Print", ReplyAction="http://tempuri.org/IPrinterServ/PrintResponse")]
        System.Threading.Tasks.Task PrintAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrinterServChannel : StoreApp.PrinterService.IPrinterServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrinterServClient : System.ServiceModel.ClientBase<StoreApp.PrinterService.IPrinterServ>, StoreApp.PrinterService.IPrinterServ {
        
        public PrinterServClient() {
        }
        
        public PrinterServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrinterServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrinterServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrinterServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Print(string text) {
            base.Channel.Print(text);
        }
        
        public System.Threading.Tasks.Task PrintAsync(string text) {
            return base.Channel.PrintAsync(text);
        }
    }
}
